import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import Footer from "@/components/Footer/Footer";
import styles from "./layout.module.css";
import Up from "@/components/Up/Up";

export const metadata: Metadata = {
   title: "Rating App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
         </head>
         <body>
            <div className={styles.wrapper}>
               <Header className={styles.header} />
               <Sidebar className={styles.sidebar} />
               <div className={styles.body}>{children}</div>
               <Footer className={styles.footer} />
               <Up />
            </div>
         </body>
      </html>
   );
}
